export const recipes = [
  {
    id: 1,
    title: 'Thang Noodle',
    category: 'Noodle',
    badge: 'Popular',
    time: '20 mins',
    servings: 4,
    difficulty: 2,
    img: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=600&q=80',
    ingredients: [
      '200g rice noodles',
      '4 cups chicken broth',
      '150g sliced chicken breast',
      '2 tbsp fish sauce',
      '1 tbsp lime juice',
      'Spring onions, bean sprouts, chilli to serve',
    ],
    instructions:
      'Boil noodles until tender, drain. Heat broth, season with fish sauce and lime. Poach chicken slices in the broth. Ladle over noodles and top with fresh herbs and condiments.',
  },
  {
    id: 2,
    title: 'Mango Sticky Rice',
    category: 'Dessert',
    badge: 'Classic',
    time: '25 mins',
    servings: 4,
    difficulty: 1,
    img: 'https://images.unsplash.com/photo-1582801205465-c0d029e85a1c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWFuZ28lMjBzdGlja3klMjByaWNlfGVufDB8fDB8fHww',
    ingredients: [
      '1 cup glutinous rice',
      '1 can (400ml) coconut milk',
      '3 tbsp sugar',
      '½ tsp salt',
      '2 ripe mangoes, sliced',
      'Toasted sesame seeds',
    ],
    instructions:
      'Soak rice overnight, steam 20 mins. Mix warm coconut milk with sugar and salt. Pour half over rice, stir and rest 10 mins. Serve with fresh mango and drizzle remaining coconut milk.',
  },
  {
    id: 3,
    title: 'Corn Spicy Salad',
    category: 'Salad',
    badge: 'Trending',
    time: '30 mins',
    servings: 2,
    difficulty: 2,
    img: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80',
    ingredients: [
      '2 ears sweet corn',
      '1 red chilli, sliced',
      '2 tbsp lime juice',
      '1 tbsp fish sauce',
      'Cherry tomatoes, halved',
      'Fresh mint and coriander',
      'Toasted peanuts',
    ],
    instructions:
      'Grill or roast corn until charred. Cut kernels off. Toss with chilli, lime juice, fish sauce, tomatoes and herbs. Top with peanuts and serve immediately.',
  },
  {
    id: 4,
    title: 'Tom Yum Soup',
    category: 'Soup',
    badge: 'Hot',
    time: '35 mins',
    servings: 3,
    difficulty: 3,
    img: 'https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=600&q=80',
    ingredients: [
      '500ml chicken stock',
      '200g shrimp',
      '2 stalks lemongrass',
      '4 kaffir lime leaves',
      '3 slices galangal',
      '2 tbsp fish sauce',
      '1 tbsp lime juice',
      'Mushrooms, chilli, coriander',
    ],
    instructions:
      'Bring stock to boil with lemongrass, lime leaves and galangal. Add mushrooms and simmer 5 mins. Add shrimp and cook until pink. Season with fish sauce and lime. Garnish with coriander.',
  },
  {
    id: 5,
    title: 'Pad Thai',
    category: 'Noodle',
    badge: 'Favourite',
    time: '20 mins',
    servings: 2,
    difficulty: 2,
    img: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
    ingredients: [
      '200g flat rice noodles',
      '150g tofu or shrimp',
      '2 eggs',
      '3 tbsp pad thai sauce',
      '2 tbsp tamarind paste',
      'Bean sprouts, spring onion',
      'Peanuts, lime, chilli flakes',
    ],
    instructions:
      'Soak noodles until soft. Stir-fry protein in hot wok, push aside and scramble eggs. Add noodles and sauce, toss vigorously. Add bean sprouts and serve with garnishes.',
  },
  {
    id: 6,
    title: 'Green Papaya Salad',
    category: 'Salad',
    badge: 'Fresh',
    time: '15 mins',
    servings: 2,
    difficulty: 1,
    img: 'https://images.unsplash.com/photo-1648421331147-9fcfab29536e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGFwYXlhJTIwc2FsYWR8ZW58MHx8MHx8fDA%3D',
    ingredients: [
      '1 green papaya, shredded',
      '2 cloves garlic',
      '2 bird chillies',
      '2 tbsp fish sauce',
      '2 tbsp lime juice',
      '1 tsp palm sugar',
      'Cherry tomatoes, green beans',
      'Dried shrimp, peanuts',
    ],
    instructions:
      'Pound garlic and chilli in mortar. Add papaya, tomatoes and green beans, lightly pound. Season with fish sauce, lime and sugar. Top with dried shrimp and peanuts.',
  },
];
